version: "3.0"
services:
  node-app:
    container_name: node-app
    build: .
    depends_on:
      - database
    mem_reservation: 500m
    ports:
      - "8080:8080"
  database:
    image: mysql
    hostname: database
    container_name: movie-db-app
    ports:
      - "1235:3306"
    environment:
      - MYSQL_DATABASE=movie-db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=sml12345
